database_connection:
  host: localhost
  port: 5432
  user: postgres
  password: your_password_here

operations:
  - name: show_db_sizes
    type: data_retrieval
    description: Display sizes of all PostgreSQL databases on the server
    sql_command: |
      SELECT 
        datname AS database_name,
        pg_database_size(datname) AS size_in_bytes
      FROM 
        pg_database
      WHERE 
        datistemplate = false
      ORDER BY 
        size_in_bytes DESC;
    parameters: []
    visualization:
      type: pie_chart
      settings:
        labels: database_name
        values: size_in_bytes
        title: Database Sizes
        colormap: Set3

  - name: show_table_sizes
    type: data_retrieval
    description: Display sizes of all tables in the current database
    sql_command: |
      SELECT 
        schemaname || '.' || relname AS table_name,
        pg_total_relation_size(schemaname || '.' || relname) AS total_size_bytes
      FROM 
        pg_stat_user_tables
      ORDER BY 
        total_size_bytes DESC;
    parameters:
      - name: database
        type: string
        description: Name of the database to analyze
    visualization:
      type: data_table
      settings:
        columns:
          - table_name
          - total_size_bytes

  - name: show_pg_config
    type: data_retrieval
    description: Display PostgreSQL configuration parameters matching a search expression
    sql_command: |
      SELECT 
        name, 
        setting, 
        unit, 
        context, 
        short_desc
      FROM 
        pg_settings
      WHERE 
        name ILIKE '%' || :search_expression || '%'
        OR setting ILIKE '%' || :search_expression || '%'
        OR short_desc ILIKE '%' || :search_expression || '%'
      ORDER BY 
        name;
    parameters:
      - name: search_expression
        type: string
        description: Search expression to filter configuration parameters
    visualization:
      type: data_table
      settings:
        columns:
          - name
          - setting
          - unit
          - context
          - short_desc

  - name: create_new_db_and_objects
    type: create_objects
    description: Create a new database with tables and cron jobs
    script: create_db_objects.py
    parameters:
      - name: db_name
        type: string
        description: Name of the new database to create
      - name: tables
        type: list
        description: List of tables to create in the new database
      - name: cron_jobs
        type: list
        description: List of cron jobs to set up
    visualization:
      type: text_output
      settings:
        display: execution_log